configuration: Release

# version format
version: 2.3.{build}

# Operating system (build VM template)
os: Windows Server 2012 R2

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
build:
  project: TestProject.sln

test:
  assemblies:
    - '**\Tools.Test.dll'